# -*- coding: utf-8 -*-
"""automate_Windy.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13JxoumlbEhYHJVq6nZMmVDM8u7OmAIkK
"""

import pandas as pd


def load_data(file_path):
    """
    Memuat dataset dari file CSV
    """
    df = pd.read_csv(file_path, sep=';')
    print(f"Dataset berhasil dimuat: {df.shape}")
    return df


def remove_duplicates(df):
    """
    Menghapus data duplikat
    """
    before = len(df)

    df = df.drop_duplicates()

    after = len(df)

    print(f"Data duplikat dihapus: {before - after}")

    return df


def cap_outliers_iqr(df, columns):
    """
    Menangani outlier menggunakan metode IQR Capping
    """

    for col in columns:

        q1 = df[col].quantile(0.25)
        q3 = df[col].quantile(0.75)

        iqr = q3 - q1

        lower_bound = q1 - (1.5 * iqr)
        upper_bound = q3 + (1.5 * iqr)

        df[col] = df[col].clip(
            lower=lower_bound,
            upper=upper_bound
        )

    print("Outlier berhasil ditangani dengan IQR Capping")

    return df


def encode_target(df):
    """
    Encoding target variable
    yes = 1
    no = 0
    """

    df['y'] = df['y'].map({
        'yes': 1,
        'no': 0
    })

    print("Target variable berhasil diencoding")

    return df


def encode_categorical_features(df):
    """
    One Hot Encoding fitur kategorikal
    """

    categorical_cols = df.select_dtypes(
        include='object'
    ).columns.tolist()

    if len(categorical_cols) > 0:

        df = pd.get_dummies(
            df,
            columns=categorical_cols,
            drop_first=True
        )

    print("Fitur kategorikal berhasil diencoding")

    return df


def preprocess_data(input_file):
    """
    Pipeline preprocessing lengkap
    """

    # Load data
    df = load_data(input_file)

    # Hapus duplikat
    df = remove_duplicates(df)

    # Fitur numerik
    numerical_cols = [
        'age',
        'balance',
        'day',
        'duration',
        'campaign',
        'pdays',
        'previous'
    ]

    # Outlier handling
    df = cap_outliers_iqr(
        df,
        numerical_cols
    )

    # Encoding target
    df = encode_target(df)

    # Encoding fitur kategorikal
    df = encode_categorical_features(df)

    return df


def save_processed_data(df, output_file):
    """
    Menyimpan dataset hasil preprocessing
    """

    df.to_csv(
        output_file,
        index=False
    )

    print(f"Dataset preprocessing berhasil disimpan:")
    print(output_file)


if __name__ == "__main__":

    INPUT_FILE = "/content/bank-full.csv"

    OUTPUT_FILE = "bank_marketing_preprocessing.csv"

    print("=" * 50)
    print("BANK MARKETING PREPROCESSING")
    print("=" * 50)

    processed_df = preprocess_data(
        INPUT_FILE
    )

    save_processed_data(
        processed_df,
        OUTPUT_FILE
    )

    print("\nDataset akhir:")
    print(processed_df.shape)

    print("\n5 Baris Pertama:")
    print(processed_df.head())

    print("\nPreprocessing selesai!")